const Bug = 'Bug-type Pokémon are characterized by their fast growing, they don\'t take long to evolve. Bug-type Pokémon live mostly (not all of them) in forests, some of them are a little harder to find because they live atop the trees.\nFrom Generation V on, it is known that Bug-type Pokémon are preferred by artists, mostly because they have beautiful colors and have a stoic and cheerful character. It can be said that Bug-type Pokémon represent the beauty of nature. Many of the bug-type pokemon evolutions are similar to the life cycles of insects like that of beetles and butterflies; i.e the first stage like larvae, second like pupae, then its final evolution into its mature, adult form. (Ironically, the Pokemon that evolves the latest out of all level-evolving Pokemon, Larvesta, happens to be a Bug-type.)\nThe known famous Bug-type trainers are: Bugsy, the Gym Leader of Azalea Town in Johto; Aaron, the first member of the Elite Four of the Sinnoh Pokémon League; Burgh, the Gym Leader of Castelia City in Unova; and Viola, the Gym Leader of Santalune City in Kalos.';
const Dark = 'The Dark type was added in Generation II to counteract the Psychic type\'s dominance of the game, by being completely immune to it and able to hit Psychic super-effectively.\nThe Dark type is represented from traits that are considered feral and untameable, specifically that born from adverse and intense complex social conditions, to that of traits that evoke a negative leaning nature, from having a nocturnal day cycle, exhibitions of unusually cruel, crafty, and clever intelligence, belligerent aggressiveness, the sentient awareness and choice to harm and/or inflict ill will, and to that of the negative end of nature and reality, such as the shadows, declination, "the survival of the fittest", destruction, comings of darker times, and to the unknown but potentially dangerous aspects of the mysterious and enigmatic.\nThe known famous Dark-type Trainers are: Karen, the fourth member of the Elite Four of the Johto Pokémon League; Sidney, the first member of the Elite Four of the Hoenn Pokémon League; Grimsley, a member of the Elite Four of the Unova Pokémon League and Nanu, an island Kahuna in Alola.';
const Dragon = 'The Dragon type is often considered an ancestral type as many Legendary Dragon-type Pokémon are revered as deities. Other Dragon-type Pokémon are frequently hard to catch and train. They also evolve late and are relatively rare. An interesting fact is that the stats of many Dragon-type Pokémon surpass the stats of other types of Pokémon.\nNotable Dragon-type users include Lance (the last member of the Kanto Elite Four and then Johto League champion), Clair (the Blackthorn City Gym Leader), Drake (the last member of the Hoenn Elite Four), Iris (Gym Leader of Opelucid City and then Unova League champion), Drayden (the Opelucid City Gym Leader) and Drasna (a member of the Kalos Elite Four).';
const Electric = 'The Electric-type is a type of Pokémon that have electricity-oriented powers. They possess electro kinetic abilities, being able to control, store, or even produce electricity.\nElectric-type Pokémon have varied habitats, from forests, praries, cities and power plants. Electric-type Pokémon are usually fast, and many of their attacks may paralyze the target. Some Electric-type Pokémon also resemble artifical objects used by humans that can relate to electricity (the Magnemite and Voltorb evolution lines and Rotom).\nSome of the Electric-type Pokémon Trainers are Lt. Surge, the third Gym Leader of Kanto; Wattson, the third Gym Leader of Hoenn; Volkner, the last Sinnoh Gym Leader; Elesa the fourth Gym Leader of Unova; Clemont, the fifth Gym Leader of Kalos; and Sophocles, a Trial Captain of Ula\'ula Island, Alola.';
const Fairy = 'The Fairy type was introduced in Generation VI to balance the metagame (the Dragon type, in particular) in a manner similar to the introduction of the Dark and Steel types in Generation II.\nFairy-type Pokémon are generally considered "cute" and tend to be at least partially pink in color and feminine in appearance overall. However, Fairy types can be incredibly powerful. Fairy types also have some magical appeal to them. As opposed to Psychic-type Pokémon, Fairy-type Pokémon have powers related to magic and the supernatural as opposed to mental power.\nThe known famous Fairy-type Pokémon Trainers are Valerie, the sixth Gym Leader of the Kalos region, and Mina, the Fairy-type Trial Captain of the Alola region.';
const Fighting = 'Pokémon of this type are specialists in melee attacks, such as punches and kicks. It could be said that they\'re the opposite to Psychic-type Pokémon because while Pokémon of that type depend primarily on special attacks, Pokémon of the Fighting type depend mostly on physical attacks. In particular, every Fighting-type attack introduced before Generation IV remained a physical attack, with special Fighting attacks only being introduced from Generation IV onwards.\nMost Fighting-type Pokémon have a human-like body shape because they represent practitioners of various martial arts, which tend to be real-world humans.\nEvery generation has introduced at least one Fighting-type specialist: Bruno, the second member of the Kanto and Johto Elite Four; Chuck, the fifth Gym Leader of the Johto region; Brawly, the second Hoenn Gym Leader; Maylene, the third Gym Leader of Sinnoh; Marshal, a member of the Unova Elite Four; Korrina, the third Gym Leader of the Kalos region; and Hala, a Kahuna of the Alola region.';
const Fire = 'It is notable for being one of the three Starter types, forming a perfectly triangular relationship with Grass and Water.\nFire-type moves are based on attacks of fire itself, and most of them can leave the status Burn. Fire types are also immune to being Burned, regardless of the type of move used that would have inflicted a Burn.\nFire Pokémon have notably fewer species compared to the other Starter types, due to a lack of natural phenomena that can be described as fire - the Slugma line, Numel line, Magmar line and Torkoal are the closest representation. Some Fire-type species are based on land animals known for their predatory instincts, such as Pyroar, Arcanine and Heatmor. The Vulpix and Fennekin lines are both based on Japanese folklore linking species of fox with fire, while curiously, the first five generations of Fire-type starter, as well as the Ponyta, Houndour and Pansear lines, are all based on animals from the Chinese zodiac.\nFamous Fire-type Pokémon Trainers include Blaine, the seventh Kanto Gym Leader; Flint, the third member of the Sinnoh Pokémon League; Chili, one of the first three Gym Leaders of Striaton City in Unova; Malva, a member of the Kalos Pokémon League.';
const Flying = 'Pokémon of this type can fly, many of them live at high altitudes, even. Most of them are birds and insects. Their power is mostly related with aerial and wind-related attacks. Most of them have wings, but there are also some of them that just float without wings, like Rayquaza and Gyarados.\nFlying has been paired with every other Pokémon type to create a species; the introduction of Fighting/Flying Hawlucha completed all possible pairings. Until Generation V no species was ever a pure Flying-type; purely Flying typing could only be obtained in battle by Porygon, Kecleon and Arceus, which all had signature moves or abilities to do so.\nFamous Flying-type Pokémon Trainers include Falkner, the first Gym Leader of the Johto region; Winona, the sixth Gym Leader of Hoenn; and Skyla, the sixth Unova Gym Leader.';
const Ghost = 'The Ghost type is notable for having few Pokémon, many of whom have low HP, and moves. In battles, the Ghost-type is useful because it\'s the only type that has two immunities: Normal and Fighting, both of which are common move types. From Generation VI onwards, Ghost-types are also immune to moves and abilities that prevent escaping, like Block and Shadow Tag.\nPokémon of this type are usually connected to fear, the dark and the afterlife. They usually live in abandoned houses, cemeteries, funeral places and uninhabited dark places such as caves. Also, Ghost-type Pokémon tend to be extremely naughty, pranking humans just to see their faces and reactions. Curiously, the more scared a human is, the more power the Ghost Pokémon will have to prank with it. At worst, some Ghost-type Pokemon may have relatively murderous behaviors, such as Jellicent preying on ships and their crews or the Litwick evolutionary family draining the life energy from people that are lost.\nFamous Ghost-type Pokémon Trainers include Agatha, third member of the Kanto Elite Four; Morty, the fourth Gym Leader of Johto; Phoebe, second member of the Hoenn Elite Four; Fantina, the fifth Gym Leader in the Sinnoh region; Shauntal, a member of the Unova Elite Four; and Acerola, a Trial Captain of Ula\'ula Island, Alola as well as its third Elite Four member.';
const Grass = 'Grass is one of the three Starter types, forming a perfectly triangular relationship with Fire and Water.Many Grass types are based on real-world plants and fungi; many such Pokémon also belong to the Plant egg group. Several Grass types are paired with the Poison type, reflecting the toxicity of several plants towards mainly humans. It is worth noting that the first five Grass-type starter lines are based on prehistoric or current species of reptile.Most Grass-types can learn "seed", "spore" or "powder" moves that inflict status (usually Poison, Paralysis or Sleep), including a unique type of status caused by Leech Seed; thus, many Grass-types employ a passive style of play during battle. In terms of direct attacks, Grass-types drain with moves like Giga Drain, or attack with leaves, vines, petals, wood or sunlight.Famous Grass-type Pokémon Trainers include Erika, fourth Gym Leader of the Kanto region; Gardenia, the second Gym Leader of Sinnoh; Cilan, one of the three Striaton Gym Leaders in Unova; and Mallow, an Akala Island Trial Captain in Alola.';
const Ground = 'Ground-type Pokémon have powers and abilities related to control of ground and earth. Ground-type Pokémon are afraid of water, like Rock-type Pokémon, unless they are Water type. Many Ground Pokémon are also partially Rock type.\nThese Pokémon are normally found in caves or rocky terrains, with the exceptions of some dual typed Pokémon. One bad thing about them is that they can\'t normally come off the ground, such as Diglett and Dugtrio, even though they are pretty good combatants when they are below the Earth\'s surface. They have powerful moves such as Earthquake and Fissure.\nFamous Ground-type Pokémon Trainers include Giovanni, the last Gym Leader of the Kanto region (also leader of Team Rocket); Bertha, a member of the Sinnoh Elite Four; Clay, the fifth Gym Leader in Unova; and Hapu, an island Kahuna in Alola.';
const Ice = 'Ice-type Pokémon stand out for being able to endure very low temperatures, as well as adapting to freezing weathers. They control ice at will. Their habitats go from the top of mountains, frozen caves and caverns or even the poles.\nMany Ice-type moves have chances of freezing the target, which prevents them from attacking until they thaw out.\nFamous Ice-type Pokémon Trainers include Lorelei, a member of the Kanto Elite Four; Pryce, the seventh Gym Leader of the Johto region\'s Mahogany Town; Glacia, a member of the Hoenn Elite Four; Candice, the seventh Gym Leader of Sinnoh\'s Snowpoint City; Brycen, once a Gym Leader in Unova, and Wulfric, the last Gym Leader in Kalos.';
const Normal = 'Among species, Normal-type Pokémon tend to be based on a variety of different real-world animals.The Normal type has been specifically engineered to lack any offensive or defensive advantage: offensively it hits no types super-effectively but two types resist it and one is immune to it, while defensively it resists no types (but is immune to one), while one type hits it super-effectively. Defensive Normal types would typically have high defensive stats while offensive Normal types would typically learn a large variety of moves.\nNormal is also used to represent some species, and even moves, that change type - notable examples include Castform, Kecleon and Arceus, who can all change type through their abilities. Conversion and Conversion 2 both change the user\'s type but are learned only by Porygon\'s evolutionary line. Hidden Power and Natural Gift are Normal-type by classification but can be any other type depending on the specific factors - Hidden Power can never be Normal-type in practice, while only one kind of Berry grants Natural Gift a Normal type.\nFamous Normal-type Pokémon Trainers include Whitney, the third Gym Leader of the Johto region; Norman, the fifth Gym Leader of Hoenn; Lenora, the second Gym Leader of Unova; Cheren, who replaces Lenora as Gym Leader in Pokémon Black 2 and White 2; and Ilima, the Trial Captain of Melemele Island, Alola.';
const Poison = 'These Pokémon have a natural toxic quality; some directly represent real-world species known for their venom, such as snakes, and some even represent pollution itself. They normally live in caves, marshes or similar places.\nA very curious fact about Poison-type Pokémon is that some of them resemble ninjas. For example, Koffing is like a smoke ball, Crobat has a ninja\'s speed and secrecy and Toxicroak has paws that make it resemble a ninja. Some Poison-types also resemble types of pollution. Garbodor represents trash pollution, Weezing represents air pollution and Muk represent sewer pollution.\nThe Poison type is related to the status effects Poisoned and Badly Poisoned, which are produced mostly by Poison-type moves.\nFamous Poison-type Pokémon Trainers include Koga, fifth Gym Leader of Kanto and now second member of the Indigo League; Janine, Koga\'s daughter who succeeded her father\'s position in Kanto; Agatha, the then-third member of the Indigo League (her main type is Ghost, but all of her Pokémon are Poison-type as well).';
const Psychic = 'Many Pokémon are of this type, and, being the type with most Legendary Pokémon, for many, the Psychic type is the most powerful. Psychic-type Pokémon tend to be very intelligent. It\'s also interesting to note that, many Psychic-type Pokémon are based/related to real scientific or mythological discoveries such as DNA and Psychokinesis.\nTo attack, they use their mind power, thus many tend to have high special stats and low physical stats. In particular, every Psychic-type attack introduced before Generation IV remained a special attack, with physical Psychic attacks only being introduced from Generation IV onwards.\nFamous Psychic-type Pokémon Trainers include Sabrina, the sixth Gym Leader in Kanto; Will, the first member of the Johto Elite Four; Tate and Liza, the seventh Gym Leaders in Hoenn; Lucian, the fourth member of the Sinnoh Elite Four; Caitlin, a member of the Unova Elite Four; and Olympia, the seventh Gym Leader in Kalos.';
const Rock = 'Rock-type Pokémon stand out for their great defense to physical attacks, however, this type is tied with the Grass-type as having the most weaknesses, with five, and Pokémon of this type are not very fast. Also, some Rock-type moves don\'t have great accuracy.\nAll Fossil Pokémon are of this type. Their fossils preserve enough material genetic to be worked with to bring them back to life, but, it can be known, that the Rock type was very abundant. They also have unique combinations to Pokémon of the present.\nThe Rock type is commonly combined with the Ground type, so they are usually confused, although they\'re not the same. Even in the anime this confusion has been present, saying that Rock-type Pokémon are immune to Electric-type attacks.\nFamous Rock-type Pokémon Trainers include Brock, the first Gym Leader of Kanto; Roxanne, first Gym Leader of the Hoenn region; Roark, first Gym Leader in Sinnoh; Grant, the second Kalos Gym Leader; and Olivia, an island Kahuna in Alola.';
const Steel = 'It was introduced in Generation II, along with the Dark type, to balance the other types. It was added to the typing of two Pokémon, Magnemite and Magneton, which were only Electric-type.\nSteel-type Pokémon stand out for having great defense against both physical and special attacks, and a large number of resistances. They tend to be heavy and thus have low Speed. Steel-types are mainly inorganic in nature, some of them representing robots and machines.\nAlong with the Rock and Ground types, Steel represents part of the Earth\'s minerals as types.\nFamous Steel-type Pokémon Trainers include Jasmine, the sixth Johto Gym Leader; Steven Stone, the Hoenn Champion; Byron, the sixth Gym Leader of Sinnoh; and Wikstrom, a member of the Kalos Pokémon League. Also, Colress, who is part of the new Team Plasma, uses Pokémon of this type as well.';
const Water = 'There are more Pokémon of this type than any other type due to the large number of marine creatures to base species from. Most Pokémon of this type also have another type, representing the biodiversity of marine creatures. Water is notably the second type to have been paired with every other type - the Fire/Water Volcanion completed all possible pairings.\nMost Water-type Pokémon are based on creatures that live on water, or use water for their disposition. Their attacks involve use of water, if not, attacks that can be done only by marine creatures (like Clamp, Crabhammer and Razor Shell).\nFamous Water-type Pokémon Trainers include Misty, the second Kanto Gym Leader; Wallace, the first eighth Hoenn Gym Leader-turned-Champion and his replacement Juan; Crasher Wake, the fourth Gym Leader of Sinnoh; Cress, one of Striaton City\'s first three Gym Leaders in Unova; Marlon, the eighth Gym Leader of Humilau City in Unova; Siebold, one of the Kalos Elite Four; and Lana, an Akala Island Trial Captain in Alola.';

export default {
    Bug,
    Dark,
    Dragon,
    Electric,
    Fairy,
    Fighting,
    Fire,
    Flying,
    Ghost,
    Grass,
    Ground,
    Ice,
    Normal,
    Poison,
    Psychic,
    Rock,
    Steel,
    Water
};
